Refactoring npid2 source code; Moving function blocks from npid

diff --git a/bin/npid2 b/bin/npid2
--- a/bin/npid2
+++ b/bin/npid2
@@ -1,5 +1,44 @@
 #!/bin/bash
 
+SCRIPT=$0
+# Routine below facilitates the full qualified paths
+if [ "`echo $0 | cut -c1`" = "." ]; then
+   SCRIPT="`pwd`/`echo "$0" | sed 's/\.\///g'`"
+elif [ "`echo $0 | cut -c1`" != "/" ]; then
+   SCRIPT="`pwd`/$0"
+fi
+
+BIN_DIR=`dirname $SCRIPT`
+PROG_DNAME=`basename $SCRIPT`
+PROG_NAME=`echo $PROG_DNAME | sed s/.$//`
+PROG_NAME2=`echo $PROG_NAME | sed s/d$//` # The correct product name
+PROG_HOME=`dirname $BIN_DIR`
+PROG_VERSION=`cat $BIN_DIR/$PROG_NAME2 | grep ^PROG_VERSION= | awk -F"=" '{print $2}'`
+
+if [ -z "$PROG_HOME" ] ; then
+  ## resolve links - $0 may be a link to PROG_HOME
+  PRG="$0"
+
+  # need this for relative symlinks
+  while [ -h "$PRG" ] ; do
+    ls=`ls -ld "$PRG"`
+    link=`expr "$ls" : '.*-> \(.*\)$'`
+    if expr "$link" : '/.*' > /dev/null; then
+      PRG="$link"
+    else
+      PRG="`dirname "$PRG"`/$link"
+    fi
+  done
+
+  saveddir=`pwd`
+
+  PROG_HOME=`dirname "$PRG"`/..
+  # make it fully qualified
+  PROG_HOME=`cd "$PROG_HOME" && pwd`
+
+  cd "$saveddir"
+fi
+
 ## =========================================================
 ## New variables that are global
 ## =========================================================
@@ -34,30 +73,6 @@ NPI="npi"
 TRY_COUNT=10
 SLEEP_TIME=5
 
-SCRIPT=$0
-# Routine below facilitates the full qualified paths
-if [ "`echo $0 | cut -c1`" = "." ]; then
-   SCRIPT="`pwd`/`echo "$0" | sed 's/\.\///g'`"
-elif [ "`echo $0 | cut -c1`" != "/" ]; then
-   SCRIPT="`pwd`/$0"
-fi
-
-BIN_DIR=`dirname $SCRIPT`
-PROG_DNAME=`basename $SCRIPT`
-PROG_NAME=`echo $PROG_DNAME | sed s/.$//`
-PROG_NAME2=`echo $PROG_NAME | sed s/d$//` # The correct product name
-PROG_HOME=`dirname $BIN_DIR`
-PROG_VERSION=`cat $BIN_DIR/$PROG_NAME2 | grep ^PROG_VERSION= | awk -F"=" '{print $2}'`
-
-## =========================================================
-## New variables that are global
-## =========================================================
-# Re-using existing bootstraps from docker
-DOCKER_DIR=${PROG_HOME}/docker
-BOOTSTRAP="bootstrap.sh"
-ENV_FILE="npi_env.sh"
-
-
 # New environmental variables
 SH_SHELL=`which sh`
 BASH_SHELL=`which bash`
@@ -67,6 +82,7 @@ RESOURCES_DIR=${BIN_DIR}/resources
 # Environment exports
 # Pending:
 #	1. Need to segregate out exports for each individual application
+#	2. Move relevant variables into npi_env.sh
 export NPI_HOME=${PROG_HOME}
 
 export NAMENODE=true
@@ -81,7 +97,7 @@ LOG_DIR=${PROG_HOME}/log
 CONSOLE_LOG=${LOG_DIR}/${PROG_DNAME}.log
 VAR_DIR=${PROG_HOME}/var
 
-# Logs
+# Component logs
 ZOOKEEPER_LOG=${LOG_DIR}/${ZOOKEEPER_APP_NAME}.log
 KAFKA_LOG=${LOG_DIR}/${KAFKA_APP_NAME}.log
 HADOOP_LOG=${LOG_DIR}/${HADOOP_APP_NAME}.log
@@ -118,8 +134,57 @@ showVersion() {
   exit 0
 }
 
+# check ulimit parameters
+check_ulimit_param() {
+  parameter=$1
+  name=$2
+  minvalue=$3
+  currentulimitvalue=`ulimit ${parameter}`
+  if [ ${currentulimitvalue} -lt ${minvalue} ]; then
+     #attempt to set ulimit
+     local sout
+     sout=$(ulimit -S ${parameter} ${minvalue} 2>&1)
+     if [ "$?" != 0 ]; then
+        log WARN "GYMPB0103W: ulimit parameter ${parameter} (${name}) is less than minimum value ${minvalue}! Fix by adding two lines to /etc/security/limits.conf: \"${USER} hard nofile ${minvalue}\" and \"${USER} soft nofile ${minvalue}\" and then log out the ${USER} user and log back in for the changes to take effect."
+        log WARN "GYMPB0104W: Standard error from ulimit command is \"${sout}\""
+     fi
+  fi
+}
+
+# test UDP tuning parameters
+check_sysctl_param() {
+  parameter=$1
+  minvalue=$2
+  currentvalue=`/sbin/sysctl ${parameter} | awk -F'= ' '{print $2}'`
+  if [ ${currentvalue} -lt ${minvalue} ]; then
+    if [ "${ROOT}" = "YES" ]; then
+       sysctl ${parameter}=${minvalue}
+    else
+       log ERROR "GYMPB0105E: sysctl parameter ${parameter}=${currentvalue} is less than required value ${minvalue}! Fix by adding \"${parameter}=${minvalue}\" to /etc/sysctl.conf and running sysctl -p as root. Alternatively, run ${PROG_NAME} as root."
+       ERRORS=$(($ERRORS + 1))
+    fi
+  fi
+}
+
+check_parameters() {
+  ERRORS=0
+  # check if root
+  if [ "${USER}" = "root" ]; then ROOT=YES; fi
+
+  if [ "${IGNORESYSCHECK}" != "Y" ]; then
+    check_ulimit_param "-n" "open files" 8096
+    check_sysctl_param net.core.rmem_default 33554432
+    check_sysctl_param net.core.rmem_max 33554432
+    check_sysctl_param net.core.netdev_max_backlog 10000
+    if [ "${ERRORS}" != "0" ]; then
+      log ERROR "GYMPB0106E: Another kernel parameter error is fatal. Exiting. Check ${CONSOLE_LOG} for GYMPB0105E errors."
+      exit 1
+    fi
+  fi
+}
+
 # ======================================
-# Source shell scripts 
+# Source relevant shell scripts 
 # ======================================
 source ${RESOURCES_DIR}/functions
 source ${RESOURCES_DIR}/dependencies
@@ -144,11 +209,13 @@ if [ $# -lt 1 ]; then
 	exit -1
 fi
 
-if [ $# -gt 2 ]; then
-	log WARNING "GYMPB0000W: Too many arguments."
+IGNORESYSCHECK="N"
+if [ "${1}" == "-ignoresyscheck" ]; then
+  export IGNORESYSCHECK="Y"
+  shift
 fi
-
 ARG1=$1
+shift
 ARG2=$2
 
 case "${ARG1}" in
